run-server:
	@go run ./cmd/server/server.go -ldflags="-X 'github.com/vincentmegia/chat/build.Environment=development' -X 'github.com/vincentmegia/chat/build.Version=v1.0.0'"

run-client:
	@go run ./cmd/client/client.go -ldflags="-X 'github.com/vincentmegia/chat/build.Environment=development' -X 'github.com/vincentmegia/chat/build.Version=v1.0.0'"
